# Generated by Django 4.0.2 on 2022-03-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('category_description', models.TextField(default='')),
                ('category_name', models.CharField(choices=[('cloth', 'Cloth'), ('food', 'Food'), ('fashion', 'Fashion'), ('book', 'Book'), ('baby-product', 'Baby Products'), ('jewelry', 'Jewelry')], default='food', max_length=15)),
                ('category_image', models.ImageField(default='', upload_to='app_static/images')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=64)),
                ('product_quantity', models.IntegerField()),
                ('product_details', models.TextField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_time', models.DateField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
