# Generated by Django 4.0.3 on 2022-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('width', models.IntegerField(default=0)),
                ('hight', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductExtraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
