# Generated by Django 4.0.3 on 2022-04-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productdimensions_productextradetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_height',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='product_width',
            field=models.CharField(default='', max_length=64),
        ),
    ]
