# Generated by Django 4.0.3 on 2022-04-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_product_height_product_product_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_width',
        ),
    ]
