# Generated by Django 4.0.3 on 2022-04-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_product_height_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDimensions',
            new_name='ProductImageDimensions',
        ),
    ]
