# Generated by Django 4.0.3 on 2022-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_product_height_product_product_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('cloth', 'Cloth'), ('food', 'Food'), ('fashion', 'Fashion'), ('book', 'Book'), ('baby product', 'Baby Products'), ('jewelry', 'Jewelry')], default='food', max_length=15),
        ),
    ]
