# Generated by Django 4.0 on 2022-02-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authmodel_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
