# Generated by Django 4.0 on 2022-02-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authmodel_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
