# Generated by Django 4.0.2 on 2022-02-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_authmodel_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authmodel',
            name='city',
        ),
    ]
