# Generated by Django 4.0.2 on 2022-03-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_authmodel_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authmodel',
            options={'verbose_name': 'Auth'},
        ),
    ]
