# Generated by Django 4.0.3 on 2022-04-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_items',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
